### PR TITLE
Added the use of the runtime/default security profile.

### PR DESCRIPTION
**Pull request by Strigix**
I've modified the container and pod securitycontexts to let this application make use of the runtime/default seccomp profile. During testing this did not seem to interrupt any functionality. Please confirm this if possible.
This is done in light of:

https://github.com/giantswarm/roadmap/issues/259

Drop a message on slack if you've got questions.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
ok when build is green

**Comment by Strigix** [comment]
The vulnerable component is version 1.27.0
The fix for this CVE is introduced in 1.34.0. 
Is it alright to just bump the minor version up with 7?

**Comment by whites11** [comment]
> The vulnerable component is version 1.27.0 The fix for this CVE is introduced in 1.34.0. Is it alright to just bump the minor version up with 7? Or would you recommend with an ignore for now? @whites11

bump at will, it it builds I'm happy

**Comment by Strigix** [comment]
This repo is not affected by the issues described in https://github.com/giantswarm/roadmap/issues/259#issuecomment-1436729770 due to the fact proper volumes have been defined in the psp.

**Pull request merged**
